const test=require('node:test'),assert=require('node:assert/strict'),D=require('discord.js');
const {install,remove,forceStop}=require('../src/emoji-install');
function gate(){let done;const promise=new Promise(r=>done=r);return {done,promise};}
function fixture(){const emojis=new D.Collection();let creates=0,deletes=0;const c={user:{id:'admin'},guild:{id:'force-stop',premiumTier:3,members:{fetch:async()=>({permissions:{has:()=>true}}),fetchMe:async()=>({id:'bot',permissions:{has:()=>true}})},emojis:{fetch:async()=>emojis,create:async({name})=>{const e={id:String(++creates),name,author:{id:'bot'},delete:async()=>{deletes++;}};emojis.set(e.id,e);return e;}}}};return {c,counts:()=>[creates,deletes]};}
test('force stop cancels uploader and queued deletion; new batches work after settling',async()=>{const {c,counts}=fixture(),started=gate(),pending=gate(),queued=gate();const create=c.guild.emojis.create;c.guild.emojis.create=async o=>{started.done();await pending.promise;return create(o);};const upload=install(c);await started.promise;const deletion=remove(c,async()=>queued.done(),true);await queued.promise;assert.match(await forceStop(c),/cancelled/);pending.done();await Promise.all([upload,deletion]);assert.deepEqual(counts(),[1,0]);assert.match(await forceStop(c),/No emoji job/);c.guild.emojis.create=create;await install(c);assert.deepEqual(counts(),[6,0]);});
test('rate limit stops job with wait time and releases lock',async()=>{const {c}=fixture();c.guild.emojis.create=async()=>{throw new (require('@discordjs/rest').RateLimitError)({route:'/guilds/:id/emojis',retryAfter:65000,timeToReset:2000,sublimitTimeout:0});};assert.match(await install(c),/65 seconds/);assert.match(await forceStop(c),/No emoji job/);});
test('administrator check and aliases',async()=>{const {c}=fixture();c.guild.members.fetch=async()=>({permissions:{has:()=>false}});await assert.rejects(forceStop(c),/Administrator/);const {parsePrefix}=require('../src/messages');assert.equal(parsePrefix('-force stop').command,'forcestopemojis');assert.equal(parsePrefix('-force stop emojis').command,'forcestopemojis');});

test('sublimit cooldown is displayed instead of generic upload failure',async()=>{const {c}=fixture();c.guild.emojis.create=async()=>{throw new (require('@discordjs/rest').RateLimitError)({route:'/guilds/:id/emojis',retryAfter:1000,timeToReset:2000,sublimitTimeout:90000});};const result=await install(c);assert.match(result,/90 seconds/);assert.doesNotMatch(result,/Discord upload failed/);});
