const test=require('node:test'),assert=require('node:assert/strict'),D=require('discord.js');
let config={},saved=[];
require.cache[require.resolve('../src/store')]={exports:{collection:()=>({updateOne:async(q,u)=>saved.push(u.$set)})}};
require.cache[require.resolve('../src/discipline')]={exports:{settings:async()=>config}};
const {escalate}=require('../src/ticket-escalation');
function fixture(){saved=[];config={support_high:'hr'};let sent=0,edits=0,granted=0;const r={_id:'123',owner:'user',guildId:'g',type:'general',reason:'Help',panelId:'panel'};const i={guildId:'g',user:{id:'staff'},guild:{roles:{fetch:async id=>({id,mentionable:true})},members:{fetchMe:async()=>({id:'bot'})}},channel:{permissionsFor:()=>({has:()=>true}),permissionOverwrites:{edit:async(id,p,o)=>{assert.equal(id,'hr');assert.equal(o.type,D.OverwriteType.Role);assert.ok(p.ViewChannel);granted++;}},send:async p=>{sent++;assert.deepEqual(p.allowedMentions.roles,['hr']);assert.ok(p.enforceNonce);},messages:{fetch:async()=>({id:'panel',edit:async p=>{edits++;p.components[0].toJSON();}})}}};return {r,i,counts:()=>({sent,edits,granted})};}
test('escalation grants access, persists high-rank support, pings and updates once',async()=>{const {i,r,counts}=fixture();await escalate(i,r);assert.equal(r.support,'hr');assert.equal(r.type,'high');assert.equal(r.escalationNotified,true);assert.deepEqual(counts(),{sent:1,edits:1,granted:1});assert.match(await escalate(i,r),/already/);assert.equal(counts().sent,1);});
test('invalid role or permissions cannot record a successful escalation',async()=>{const {i,r,counts}=fixture();i.guild.roles.fetch=async()=>null;await assert.rejects(escalate(i,r),/valid Senior/);assert.equal(saved.length,0);assert.equal(counts().sent,0);const f=fixture();f.i.channel.permissionsFor=()=>({has:()=>false});await assert.rejects(escalate(f.i,f.r),/Manage Roles/);assert.equal(saved.length,0);});
test('failed notification remains retryable; panel failure remains pending for recovery',async()=>{const {i,r}=fixture();const send=i.channel.send;i.channel.send=async()=>{throw Error('unavailable');};await assert.rejects(escalate(i,r),/unavailable/);assert.equal(r.escalationNotified,undefined);i.channel.send=send;i.channel.messages.fetch=async()=>{throw Error('missing panel');};await escalate(i,r);assert.equal(r.escalationNotified,true);assert.ok(saved.some(s=>s.panelPending===true));assert.ok(!saved.some(s=>s.panelPending===false));});
test('ticket layout has reference text and controls within Discord limits',()=>{const p=require('../src/legacy-layout').ticketNotice({_id:'123456',owner:'u',type:'general',reason:'x'.repeat(1000),extra:'y'.repeat(1000)});const j=p.components[0].toJSON();const text=j.components.filter(c=>c.type===10).map(c=>c.content).join('');assert.match(text,/Thanks <@u> for contacting support/);assert.match(text,/12 hours/);assert.match(text,/TICKET-123456/);assert.match(text,/Valenti Crime Family/);assert.ok(text.length<4000);const controls=j.components.find(c=>c.type===1).components;assert.deepEqual(controls.map(c=>c.label),['Claim','Close','Escalate']);});
