export const DISCORD_GUIDELINES = [
    '## Discord Guidelines',
    '## 1. Respect Everyone',
    '- Treat all members with respect at all times.',
    '- No harassment, discrimination, hate speech, or disrespecting people.',
    '- Keep arguments civil.',
    '## 2. Follow Discord TOS',
    '- All Discord Terms of Service and Community Guidelines apply.',
    '## 3. No NSFW or Explicit Content',
    '- Keep all chats appropriate for a roleplay community.',
    '## 4. No Spamming or Advertising',
    '- No spam, excessive emojis, caps, or mic spam.',
    '- No advertising other servers, services, or social media without staff permission.',
    '## 5. Use Channels Correctly',
    '- Use channels only for their intended purpose.',
    '- Commands must be used only in designated command channels.',
    '## 6. Staff Interaction',
    '- Do not argue with staff. If you have an issue, open a ticket respectfully.',
    '## 7. Account Responsibility',
    '- You are responsible for your account and actions.',
    '## 8. Enforcement',
    '- Rule violations may result in moderation based on severity and repeat offenses.',
    '## 9. Discord Usernames / Display Names',
    '- Follow the server naming requirements.',
    '## 10. Common Sense',
    '- Use common sense and do not look for loopholes.',
].join('\n');

// The dashboard's existing non-Discord regulations cover in-game roleplay
// voice channels. Keep this shared so the rules channel and dashboard cannot
// drift apart.
export const GAME_GUIDELINES = [
    '## Game and Roleplay Voice Guidelines',
    '## 1. Joining RP Voice Channels',
    '- Do not join RP voice channels if you are not in-game.',
    '- Do not join RTOs if you are not currently on that team.',
    '- Do not join scene voice channels you are not a part of or were not invited to join.',
    '## 2. Use RP Voice Channels for Their Intended Purpose',
    '- Respect active scenes and keep roleplay channels focused on roleplay.',
    '## 3. RTO Rules',
    '- RTO means Radio Traffic Only.',
    '- Keep transmissions realistic, brief, and direct.',
    '- Do not talk over another unit unless required by the situation.',
    '## 4. Voice Channels',
    '- Use RTO, civilian, criminal, scene, business, and traffic-stop channels only for their intended purpose.',
    '## 5. Remaining in Character',
    '- Remain in character while inside active roleplay voice channels.',
    '- Move to an appropriate non-RP channel when you need to speak out of character.',
].join('\n');

export const TICKET_TERMS = [
    '## Ticket Terms of Service',
    'Before opening a ticket in our server, you should know the following rules about opening a ticket so you do not accidentally break any of them. Below, you will find the rules in order. Please obey them, as failure to do so may result in punishment.',
    '',
    '1. We have the right to close a ticket for **ANY** reason.',
    '2. Please do not argue with staff, as they have the final say.',
    '3. If you complain or yell at ownership about an issue, your ticket will be closed.',
    '4. Please be respectful toward everyone.',
    '5. Do not spam in tickets.',
    '6. If you open a ticket on an alternate account to appeal your ban, you will be banned. Ban appeals must follow the server\'s approved appeal process.',
    '',
    'If you break any of these rules and then complain about the outcome, your ticket may be closed immediately. Thank you.',
].join('\n');

export const SUPPORT_FAQ = [
    '## Frequently Asked Questions',
    '### How do I partner with LARP?',
    'Use `/partnership request` to open the partnership request form. Please use a permanent Discord invite and include your complete server advertisement.',
    '',
    '### How do I verify?',
    'Head to <#1541264318799159326> and follow the verification instructions there.',
    '',
    '### How do I become a Moderator?',
    'Use the application options in the server dashboard. Make sure your written responses use proper spelling, punctuation, and grammar and meet all application requirements.',
    '',
    '**Do not ask for your application to be read.**',
].join('\n');
