const {randomUUID}=require('node:crypto');
const {collection,locked}=require('./store');
const USER_IDS=['1066264414359138304','1262469782897295461'];
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const jobs=()=>collection('dm_tests');
function parse(text){const match=/^([\s\S]+)\s+(\d+)$/.exec(text.trim());if(!match||!match[1].trim()||match[1].length>1800||Number(match[2])<1||Number(match[2])>50)throw new Error('Use -spamcool your message 1–50 (message up to 1,800 characters), or -spamcool stop.');return {text:match[1].trim(),count:Number(match[2])};}
async function runBatch(users,job,wait=pause){
 if(!users.every(u=>USER_IDS.includes(u.id))||job._id!=='self-dm'||!Number.isInteger(job.count)||job.count<1||job.count>50)throw new Error('Self-DM restriction violated.');
 try{for(let n=0;n<job.count;n++){const state=await jobs().findOne({_id:'self-dm'});if(state?.runId!==job.runId||state.status!=='running')return;for(const user of users)await user.send({content:job.text,allowedMentions:{parse:[]}});await jobs().updateOne({_id:'self-dm',runId:job.runId},{$set:{sent:n+1}});if(n+1<job.count)await wait(2000);}await jobs().updateOne({_id:'self-dm',runId:job.runId,status:'running'},{$set:{status:'completed'}});}catch(e){console.error('Self-DM test stopped:',e.code||e.name);await jobs().updateOne({_id:'self-dm',runId:job.runId,status:'running'},{$set:{status:'failed'}}).catch(()=>{});}}
async function request(user,input,client){if(!USER_IDS.includes(user.id))throw new Error(`Only accounts ${USER_IDS.join(' and ')} can use this self-DM command.`);if(input.trim().toLowerCase()==='stop'){await jobs().updateOne({_id:'self-dm',status:'running'},{$set:{status:'cancelled'}});return 'Stopped your DM test. A message already being sent may still arrive.';}const args=parse(input);const job=await locked('self-dm:job',async()=>{const previous=await jobs().findOne({_id:'self-dm'});if(previous?.nextAllowed>Date.now())throw new Error('Please wait 10 minutes between DM tests. You can still use -spamcool stop.');const next={_id:'self-dm',...args,runId:randomUUID(),status:'running',sent:0,nextAllowed:Date.now()+600000};await jobs().replaceOne({_id:'self-dm'},next,{upsert:true});return next;});const users=await Promise.all(USER_IDS.map(id=>client.users.fetch(id)));void runBatch(users,job).catch(e=>console.error('Self-DM test failed:',e.code||e.name));return `Sending up to ${job.count} messages to both authorized DMs, two seconds apart. Use -spamcool stop to cancel. This is not a hosting keep-alive.`;}
async function handle(message){if(message.author.bot||message.webhookId)return;try{const result=await request(message.author,message.content.replace(/^-spamcool\s*/i,''),message.client);await message.reply({content:result,allowedMentions:{parse:[],repliedUser:false}});if(message.guild)await message.delete().catch(()=>{});}catch(e){await message.reply({content:e.name==='Error'?e.message:'DM test could not start. Check the bot logs.',allowedMentions:{parse:[],repliedUser:false}}).catch(()=>{});}}
module.exports={USER_IDS,parse,runBatch,request,handle};
